### ISSUE TITLE
Better detection of travis-ci vs pro

### ISSUE THREAD

**Issue by igorspasic** [kt3k/coveralls-gradle-plugin#15]
Currently if there is an env variable for repo token, plugin assumes it is travis-pro. This is not entirely correct. Since I have some integration tests, I am sending jacoco reports from my computer, not from travis. For this I need the env variable to be set, and yet I am using travis-ci not pro.

**Comment by Kevin-Lee** [comment]
I have this problem too. The problem can be easily solved if `coveralls-gradle-plugin` doesn't ignore the environment variables for the `serviceName` which is `CI_NAME`. [AS you can see](/kt3k/coveralls-gradle-plugin/blob/master/src/main/groovy/org/kt3k/gradle/plugin/coveralls/domain/ServiceInfoFactory.groovy#L19), it is not used at all. So I think the `CI_NAME` should be also checked [here](/kt3k/coveralls-gradle-plugin/blob/master/src/main/groovy/org/kt3k/gradle/plugin/coveralls/domain/ServiceInfoFactory.groovy#L101) and used [here](/kt3k/coveralls-gradle-plugin/blob/master/src/main/groovy/org/kt3k/gradle/plugin/coveralls/domain/ServiceInfoFactory.groovy#L19).

**Comment by Kevin-Lee** [comment]
I've just uploaded the fixed one to [my bintray repo](https://bintray.com/kevinlee/maven/coveralls-gradle-plugin) and it works. Now I can see Coveralls's test coverage results.

If you want to test it, add the following info accordingly in your `build.gradle`.
```gradle
buildscript {
  repositories {
    jcenter()
    mavenCentral()
    maven {
      url  "http://dl.bintray.com/kevinlee/maven"
    }
  }
  dependencies {
    classpath 'org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.3.2'
  }
}
```
