### ISSUE TITLE
Error:Unable to load class 'org.codehaus.groovy.runtime.typehandling.ShortTypeHandling'

### ISSUE THREAD

**Issue by viacheslavokolitiy** [kt3k/coveralls-gradle-plugin#23]
Hello everyone. I'm using Android Studio 0.8.4 and want to use coveralls-gradle-plugin but I can't. Strange bug appears. There is my buildscript

<pre>apply plugin: 'cobertura'
apply plugin: 'com.github.kt3k.coveralls'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:0.12.+'
        classpath 'net.saliman:gradle-cobertura-plugin:2.0.0'
        classpath 'org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

cobertura.coverageFormats = ['html', 'xml']

allprojects {
    repositories {
        mavenCentral()
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.0'
}
</pre>

It seems, that Android is unsupported yet ?

**Comment by tamminh** [comment]
Check your jdk version!
