### ISSUE TITLE
Multi-project example

### ISSUE THREAD

**Issue by ben-manes** [kt3k/coveralls-gradle-plugin#32]
Your plugin was working great until I [moved](https://github.com/ben-manes/caffeine) to a multi-project layout. It seemed to not aggregate the jacoco reports and send each individually, so only one module was shown. I fixed this by having the reports appended and stored at the root project's build directory. The html report from jacoco comes out great.

Coveralls unfortunately can't find the source, so nothing appears on the dashboard. The plugin gives the following output:
```shell
:coveralls
service name: travis-ci
service job id: 46289337
repo token: null
No source file found on the project: "caffeine"
With coverage file: /home/travis/build/ben-manes/caffeine/build/reports/jacoco/test/jacocoTestReport.xml
```

The closed multi-project issues lead to a non-existent repository or oblac/jodd's manual invocation. An example of how to setup this plugin for multi-project would be really useful.

**Comment by ben-manes** [comment]
I was able to work this out using an aggregated Jacoco report and setting the plugin's sourceDirs and jacocoReportPath accordingly. See `build,gradle` and `code_coverage.gradle` if interested.

**Comment by kt3k** [comment]
Thanks!

The above info is very helpful for me. I will put this workaround to readme. Thanks!
