### ISSUE TITLE
Support for Snap

### ISSUE THREAD

**Issue by cv** [kt3k/coveralls-gradle-plugin#34]
Hi!

I'm currently using [Snap CI](https://snap-ci.com) and I'd like to contribute a patch to make the detection and setup a little easier. The environment variables that Snap sets seem enough to populate the `ServiceInfo` object and get things going, but as I'm unfamiliar with the plugin code, I might be overlooking something. Is there anything else to it, or should I go ahead and submit a PR?

Cheers!

**Comment by kt3k** [comment]
> The environment variables that Snap sets seem enough to populate the ServiceInfo object

That must be sufficient to support another CI service.

Patches are always welcome!

Thanks,

**Comment by cv** [comment]
Excellent, pull request submitted as #35. Thanks! :smile:
