### ISSUE TITLE
Plugin assumes report XML in wrong location

### ISSUE THREAD

**Issue by knub** [kt3k/coveralls-gradle-plugin#37]
Hi,

first of all, thank you for the nice plugin :).

I am using jacoco, but have some problems with the report xml.
Executing
> ./gradlew jacocoTestReport coveralls

ends with:

> No report file available: [app/build/reports/cobertura/coverage.xml, /home/travis/build/knub/bookly/app/build/reports/jacoco/test/jacocoTestReport.xml]

For some reason, my jacocoTestReport.xml is in
> app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml

Is there some way to configure the path to the report XML?

**Comment by knub** [comment]
Alright, you can configure this via

```
coveralls {
	jacocoReportPath 'build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml'
}
```

Maybe add this to the README ;).

**Comment by kt3k** [comment]
You are right, we should have documented it in README (or maybe in the error message)

Thanks for the feedback!

**Comment by shubhamchaudhary** [comment]
I also had the same problem. Some documentation in readme would be nice :)
