### ISSUE TITLE
Reports only the last subproject if project with multiple subprojects is used

### ISSUE THREAD

**Issue by Flowdalic** [kt3k/coveralls-gradle-plugin#38]
I've added the coveralls-gradle-plugin to Smack with https://github.com/igniterealtime/Smack/commit/03206fcbf6e5c4a9eb6406536c0214df77b7c1dc?diff=unified, but it appears that only the last reported subproject is used for the analysis at https://coveralls.io/r/igniterealtime/Smack. That is, only the test coverage for `smack-tcp` appears to be shown there, which is also the last project the coveralls-gradle-plugin reported as per https://travis-ci.org/igniterealtime/Smack#L1478.

I'm not sure if this is an issue with
- my configuration
- coveralls-gradle-plugin
- https://coveralls.io

Any help is appreciated. Thank you.

**Comment by Flowdalic** [comment]
Finally I was able to solve the issue for my project with some modifications to build.gradle: https://github.com/igniterealtime/Smack/commit/4d9bd6f216c7d6bde919e6f6a588b4658f08e6fa

I think it would be better if the coveralls-gradle-plugin would simply scan the subprojects for the relevant plugins (e..g jacoco), collecting and bundling the results of the relevant tasks (e.g. jacocoTestReport) and submitting it to coveralls.

**Comment by gliptak** [comment]
Functionaljava also only displays last subproject

https://coveralls.io/github/functionaljava/functionaljava

**Comment by kt3k** [comment]
I think merging reports is too much task for this plugin. Closing in favor of the above workaround.
