### ISSUE TITLE
coveralls-gradle-plugin can't find source

### ISSUE THREAD

**Issue by wgx731** [kt3k/coveralls-gradle-plugin#39]
Hi @kt3k ,

Thanks for the awesome coveralls-gradle-plugin, but I am facing a small issue using it. Please see [build.gradle](https://github.com/wgx731/HubTurbo/blob/ci/build.gradle) and [CI output](https://travis-ci.org/wgx731/HubTurbo/builds/56211242), for some reason, `coveralls task` can't find the source file for the root project, do you have any hint on how I can fix this?

Thank you very much.

Best Regards,
GaoXiang (Eric)

**Comment by invasionofsmallcubes** [comment]
I have the very same issue with my android project:

https://github.com/invasionofsmallcubes/3gScheduler

https://github.com/invasionofsmallcubes/3gScheduler/blob/master/build.gradle

https://travis-ci.org/invasionofsmallcubes/3gScheduler/builds/106060227

**Comment by sankarbhavanib** [comment]
we are also facing same issue https://travis-ci.org/paypal/PayPal-Java-SDK

**Comment by Poeschl** [comment]
Same here: https://github.com/Poeschl/KotlinDecider | https://travis-ci.org/Poeschl/KotlinDecider

Maybe here the differenet source folder for kotlin confuses the plugin.

**Comment by mike011** [comment]
You might have to specify the location of your coverage file. For example:

```
coveralls {
    jacocoReportPath 'app/build/reports/jacoco/test/jacocoTestReport.xml'
}
```

**Comment by Poeschl** [comment]
@mike011 Maybe thats not doing anything, since the xml is found but the right source folders are not known by the plugin.

I found now a workaround for my kotlin project with an additional configuration to get the sources recognised: 
```groovy
coveralls {
    sourceDirs += ['src/main/kotlin']
}
```

**Comment by lfoppiano** [comment]
Hi, I'm having the same problem ([gradle.build](https://github.com/kermitt2/grobid/blob/dropwizard-service/build.gradle)) ([.travis.yml](https://github.com/kermitt2/grobid/blob/dropwizard-service/.travis.yml)) I'm a bit confused, with 'source' do you mean the source code or the xml report generated by cobertura?

**Comment by vgaidarji** [comment]
Working configuration for me ([Kotlin project](https://github.com/vgaidarji/dependencies-overview)):
```
coveralls {
    sourceDirs = files(sourceSets.main.kotlin.srcDirs).files.absolutePath
}
```

Coveralls Gradle plugin - **2.8.2**
JaCoCo - **0.7.9**

**Comment by kt3k** [comment]
@Poeschl's and @vgaidarji's workarounds seem working.

Closing because this issue is old.
