### ISSUE TITLE
Extension has unused properties

### ISSUE THREAD

**Issue by jacob-meacham** [kt3k/coveralls-gradle-plugin#42]
Right now the extension has saveAsFile and saveFilePath, neither of which seem to appear anywhere else in the code base. These should probably be removed, or implemented (I'd be happy to do it myself, but I'm not sure which of the above is the approach you'd like to take).

Thanks!

**Comment by kt3k** [comment]
Good catch.
I would really appreciate it if you implemented the feature of saving JSON as a file. It must be useful when somebody wants to use this plugin in polyglot projects and in combination with some other coveralls reporters, such as cpp-coveralls, php-coveralls, python-coveralls etc. (Although nobody seems to be trying it for the moment, I believe somebody will need it someday.)
