### ISSUE TITLE
Could not evaluate onlyIf predicate for task ':coveralls'. > Could not find property 'isCI' on task ':coveralls'.

### ISSUE THREAD

**Issue by lpellegr** [kt3k/coveralls-gradle-plugin#49]
I applied configuration as explained in README. Unfortunately, when I run my gradle project with _coveralls_ task from Jenkins, I get the following error:

```
* Where:
Build file 'C:\Users\Administrator\jenkins\workspace\workflow-catalog\jdk\JDK8\label\Windows\build.gradle' line: 130

* What went wrong:
Could not evaluate onlyIf predicate for task ':coveralls'.
> Could not find property 'isCI' on task ':coveralls'.
```

The `gradle.build` file I use is available below:

https://github.com/ow2-proactive/workflow-catalog/blob/master/build.gradle

Is there some configuration to apply on Jenkins related to this plugin? or environnent variables to define?

**Comment by kt3k** [comment]
Ah, README is a bit misleading.

Maybe you should remove this line. (line: 130)

```
    onlyIf { isCI }
```

or entire this block

```
tasks.coveralls {
    dependsOn 'check'
    onlyIf { isCI }
}
```

**Comment by lpellegr** [comment]
@kt3k Unfortunately, if I remove line 130 or the whole block, when I run coveralls task, either from Jenkins or my local environment, I get the following message:

```
no available CI service
```

Did I miss something?

**Comment by lpellegr** [comment]
I had to define an environment variable called `COVERALLS_REPO_TOKEN` with the appropriate value.
