### ISSUE TITLE
JDK 8 required? Error:Cause: org/kt3k/gradle/plugin/CoverallsPlugin : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by Petikoch** [kt3k/coveralls-gradle-plugin#54]
Hi,

today I upgraded your plugin from 2.4.0 to 2.6.0 in a Java **7** project.

I got an error `Error:Cause: org/kt3k/gradle/plugin/CoverallsPlugin : Unsupported major.minor version 52.0`. Obviously the plugin needs Java **8** in version 2.6.0? Right?

Would be nice to have a hint regarding compatibility / requirements in the README.md.

What do you think?

Best regards from Switzerland,
Peti

**Comment by kt3k** [comment]
Sorry for that. That was completely a mistake. I supposed to support at least oracle jdk 7 and 8.

I've published v2.6.3 to maven & bintray. That should work with Java 7.

Thanks,

**Comment by Petikoch** [comment]
Thanks a lot for the quick reaction. v2.6.3 works fine with Java 7!

**Comment by aalmiray** [comment]
Unfortunately `2.7.0` brought back the problem. The binaries were compiled with JDK8 as target. I've got the following error in a Travis build set to `oraclejdk7`

    > java.lang.UnsupportedClassVersionError: org/kt3k/gradle/plugin/CoverallsPlugin : Unsupported major.minor version 52.0

**Comment by kt3k** [comment]
Sorry. I'll fix it soon.

**Comment by kt3k** [comment]
Published v2.7.1 to maven central and jcenter. It must work with java 7.

Thanks for the support! @aalmiray
