### ISSUE TITLE
Tell coveralls the report path for multiple flavors?

### ISSUE THREAD

**Issue by joshrlesch** [kt3k/coveralls-gradle-plugin#58]
How would you go about telling the coveralls plugin the report path if Im using multiple flavors?
For example:
`jacocoReportPath = "${buildDir}/reports/coverage/<flavor>/debug/report.xml"`

**Comment by kt3k** [comment]
This plugin itself doesn't have the feature of merging the multiple jacoco reports. Instead, you can merge coverage reports of JaCoCo by configuring `JacocoReport` task.

Example Settings: https://github.com/ben-manes/caffeine/blob/master/build.gradle
Doc of JacocoReport: https://docs.gradle.org/current/dsl/org.gradle.testing.jacoco.tasks.JacocoReport.html
