### ISSUE TITLE
Gcovr support for iOS Builds using the "gradle-xcodePlugin"

### ISSUE THREAD

**Issue by jaredsburrows** [kt3k/coveralls-gradle-plugin#59]
XcodePlugin from OpenBakery uses Gcovr. Can we get this plugin to support pushing those "xml" coverage files to Coveralls?

See https://github.com/openbakery/gradle-xcodePlugin and https://github.com/openbakery/gradle-xcodePlugin/blob/master/Documentation/Parameters.md#coverage

**Comment by kt3k** [comment]
In that case, I recommend you use codecov.io instead of coveralls. Codecov.io's API accepts gcov format directly. See the document https://codecov.io/api#post-report

**Comment by jaredsburrows** [comment]
I still used coveralls, I just used `cpp-coveralls` found here: https://github.com/eddyxu/cpp-coveralls

See my example here:
https://github.com/jaredsburrows/ios-gradle-swift-template
and
https://github.com/jaredsburrows/ios-gradle-objc-template

**Comment by jaredsburrows** [comment]
@kt3k Hey, just to confirm, your plugin already works with cobertura!

See here: https://github.com/jaredsburrows/ios-gradle-swift-template/blob/master/build.gradle#L39

```
coveralls {
    coberturaReportPath = './build/coverage/cobertura.xml'
}
```

**Comment by kt3k** [comment]
Ah, gcovr's xml is compatible with cobertura format.. Thanks for sharing!
