### ISSUE TITLE
customize the path to find the code coverage file instead of the default location

### ISSUE THREAD

**Issue by helenren** [kt3k/coveralls-gradle-plugin#69]
I am using gradlew to do build/tests, which with code coverage enabled. Somehow, the code coverage file generated at different location (.../libs/SalesforceAnalytics/build/reports/debug/report.xml) than the plug trying to find it (.../libs/SalesforceAnalytics/build/reports/jacoco/test/jacocoTestReport.xml). So, hit this error:

No report file available: [/home/jenkins/workspace/coveralls/libs/SalesforceAnalytics/build/reports/cobertura/coverage.xml, /home/jenkins/workspace/coveralls/libs/SalesforceAnalytics/build/reports/jacoco/test/jacocoTestReport.xml]

How does plugin to figure out the path to find the report, and Is there a way to configure it to other location?

**Comment by helenren** [comment]
I use this to enable code coverage in my project: 

buildTypes {
    debug {
      testCoverageEnabled = true
    }
  }

**Comment by kt3k** [comment]
Hello

Please try using `jacocoReportPath` option of the plugin. For example, see https://github.com/ben-manes/caffeine/blob/master/build.gradle#L135

**Comment by helenren** [comment]
After configure jacocoReportPath as this: 
coveralls {
  jacocoReportPath = "${buildDir}/reports/coverage/debug/report.xml"
}
got following error:

21:48:36 :libs:SalesforceAnalytics:coveralls FAILED
21:48:36 
21:48:36 FAILURE: Build failed with an exception.
21:48:36 
21:48:36 * What went wrong:
21:48:36 Execution failed for task ':libs:SalesforceAnalytics:coveralls'.
21:48:36 > org.apache.http.entity.mime.content.ByteArrayBody.<init>([BLorg/apache/http/entity/ContentType;Ljava/lang/String;)V

**Comment by helenren** [comment]
here is the build.gradle file I used: https://github.com/helenren/SalesforceMobileSDK-Android/blob/dev/libs/SalesforceAnalytics/build.gradle

**Comment by kt3k** [comment]
>21:48:36 > org.apache.http.entity.mime.content.ByteArrayBody.([BLorg/apache/http/entity/ContentType;Ljava/lang/String;)V

Probably this is the same as #61 
Please try the version '2.5.0-x' instead of '2.6.3'.

**Comment by helenren** [comment]
tried version 2.7.1, the issue is gone. Thanks. 

While hit another issue for using coverage/coveralls as one check status for protected branch on github. Even there is report published to https://coveralls.io, there is no comments posted to my pull request, and the check shows "Waiting for status for be repor..." Here is my pull request: https://github.com/helenren/SalesforceMobileSDK-Android/pull/47. And here is my page on coverall.io: https://coveralls.io/github/helenren/SalesforceMobileSDK-Android?branch=dev.

**Comment by helenren** [comment]
anyone can help me on this? Thanks

**Comment by kt3k** [comment]
This plugin only covers sending of coverage data to coveralls server. The github comments and status changes come directly from coveralls servers and which is what this plugin does not control. So you should try the same build several times and if it doesn't work, you should ask to the coveralls support team.

**Comment by marioluan** [comment]
I had the same issues as you guys, but now it is working properly.

Here is a working example: [https://github.com/marioluan/java-sorting-algorithms/blob/master/build.gradle](https://github.com/marioluan/java-sorting-algorithms/blob/master/build.gradle).

**Comment by kt3k** [comment]
Closing because original issue seems resolved.
