### ISSUE TITLE
add kotlin support

### ISSUE THREAD

**Issue by Gogomoe** [kt3k/coveralls-gradle-plugin#77]
I'm failed to send the report to Coveralls
got following log:
```
:coveralls
service name: travis-ci
service job id: 246121223
repo token: present (not shown for security)
No source file found on the project: "ForeverNight"
With coverage file: /home/travis/build/gogo81745/ForeverNightEngine/build/reports/jacoco/test/jacocoTestReport.xml
```
Finally, I know the reason is that my project use kotlin only
[refer to this](https://github.com/kt3k/coveralls-gradle-plugin/blob/master/src/main/groovy/org/kt3k/gradle/plugin/coveralls/domain/JacocoSourceReportFactory.groovy#L40)
```
project.plugins.withType(GroovyPlugin) {
	targetSrcDirs += project.sourceSets.main.groovy.srcDirs
}

project.plugins.withType(ScalaPlugin) {
	targetSrcDirs += project.sourceSets.main.scala.srcDirs
}
```
But there is no kotlin here. That's why the plugin find no source file
So I add an additional configuration
```
coveralls {
    project.extensions.coveralls.sourceDirs += project.sourceSets.main.kotlin.srcDirs
}
```
[It's like this](https://github.com/kt3k/coveralls-gradle-plugin/issues/39#issuecomment-232600209)
```
coveralls {
    sourceDirs += ['src/main/kotlin']
}
```
It is working now.
I hope to add support for Kotlin.

**Comment by kt3k** [comment]
PRs are welcome!

**Comment by gogo81745** [comment]
Sorry , I am not familiar with gradle and groovy
In fact , I just started using gradle
I don't know how to fix it 😅

**Comment by kt3k** [comment]
This was duplicate of #63
