### ISSUE TITLE
javax.net.ssl.SSLHandshakeException with oraclejdk7 on Travis

### ISSUE THREAD

**Issue by Horcrux7** [kt3k/coveralls-gradle-plugin#78]
I receive the follow error:
```
:coveralls
service name: travis-ci
service job id: 258176910
repo token: null
:coveralls FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':coveralls'.
> javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
With oraclejdk8 its work. I think the cause is that there are some root certificates are missing in Java 7. Any workaround?

https://travis-ci.org/i-net-software/jlessc/jobs/258176910

**Comment by kt3k** [comment]
I think this is a issue of travis or coveralls.io (web server).
Please try workarounds in https://github.com/travis-ci/travis-ci/issues/7094

I also recommend switching to codecov.io if the above doesn't work for your project. It doesn't require any plugin like this one.

**Comment by kt3k** [comment]
Closing old issues.
