### ISSUE TITLE
No source file found on the project

### ISSUE THREAD

**Issue by jshvarts** [kt3k/coveralls-gradle-plugin#80]
First of all, thanks for the plugin!

Secondly, can anyone suggest how to troubleshoot this? It's an Android project written in Java. https://travis-ci.org/jshvarts/CleanArchitecture/builds/311086312

Thanks in advance!

:coveralls
service name: travis-ci
service job id: 311086313
repo token: null
No source file found on the project: "CleanArchitecture"
With coverage file: /home/travis/build/jshvarts/CleanArchitecture/build/reports/jacoco/test/jacocoTestReport.xml
BUILD SUCCESSFUL

**Comment by kt3k** [comment]
Can you check where jacocoTestReport.xml is placed after the test? This plugin looks for `build/reports/jacoco/test/jacocoTestReport.xml` by default. If the report is generated somewhere else, you can configure the path like:

```groovy
coveralls {
  jacocoReportPath = 'path/to/jacocoTestReport.xml'
}
```
see also [this code search](https://github.com/search?q=jacocoReportPath&type=Code&utf8=%E2%9C%93)

**Comment by jshvarts** [comment]
Same location as is expected: build/reports/jacoco/test/jacocoTestReport.xml

I have a separate jacoco config file and set the location using:

     reports {
        	html.enabled = true
		xml {
			enabled = true // coveralls plugin depends on xml format report
			destination "${rootDir}/build/reports/jacoco/test/jacocoTestReport.xml" 
		}
	}

**Comment by maboueita** [comment]
Hey @jshvarts - coming across the same issue. I assume you had found a solution?

**Comment by tonyshkurenko** [comment]
Any solution?
