### ISSUE TITLE
repo token: null No source file found on the project

### ISSUE THREAD

**Issue by lemikistu** [kt3k/coveralls-gradle-plugin#89]
Hi I have the following error;

https://travis-ci.com/lemikistu/Android-Alternative-Animations/builds/111947545

build.gradle

https://github.com/lemikistu/Android-Alternative-Animations/blob/master/build.gradle

I am new to using this kind of tools.Therefore sorry for easy mistakes.As you can see from commits I have tried almost all combinations.I managed to get Travis working fine and it builds fine with this plugin.Issue is plugin never find source or reports and always skips coverage check for some reason. That's why my coveralls is not updated with any of Travis builds.

Thanks.

**Comment by kt3k** [comment]
You need to generate jacoco (or cobertura) coverage report to use this plugin. Probably [this article](https://engineering.rallyhealth.com/android/code-coverage/testing/2018/06/04/android-code-coverage.html) would help.

**Comment by kt3k** [comment]
Closing because this doesn't seem an issue of this plugin.
