### ISSUE TITLE
Version 2.8.3 or 2.8.4?

### ISSUE THREAD

**Issue by bwaldvogel** [kt3k/coveralls-gradle-plugin#94]
The README declares `v2.8.3` as latest version. However, my build fails when trying to resolve that version.
I noticed that [plugins.gradle.org](https://plugins.gradle.org/plugin/com.github.kt3k.coveralls) lists `2.8.4` as latest version which seems to work.

Which is the latest version to be used? Could you update the README accordingly?

**Comment by kt3k** [comment]
Thanks for reporting this! We tested new publishing flow and were trying publishing several times. As a result the version didn't match in github and plugin portal.

We updated the version number in master branch! https://github.com/kt3k/coveralls-gradle-plugin/commit/602fbf4ccdbeff0d962b1ff3e1b6d301e11e97ac
