### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by lorenzleutgeb** [kt3k/coveralls-gradle-plugin#98]
This plugin does not recognize if it is being run inside [GitHub Actions](https://github.com/features/actions) and will therefore hit the following case:

https://github.com/kt3k/coveralls-gradle-plugin/blob/09a14ecc12bcf32832aa0aaf00c8914d62ec7d44/src/main/groovy/org/kt3k/gradle/plugin/coveralls/domain/ServiceInfoFactory.groovy#L98-L107

For a start, consider the following two docs:
- [Default Environment Variables](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables#default-environment-variables)
- [Contexts](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#contexts)

For example, to check for GitHub Actions, you can use:
```groovy
private static boolean envIsGithubActions(Map<String, String> env) {
   env.get('GITHUB_ACTIONS') == 'true'
}
```

To get more information, especially about associated PRs, you will have to inspect the file pointed at by the envvar `GITHUB_EVENT_PATH`, like here: https://github.com/actions/toolkit/blob/99d3ad0a6473e7e7906681627a450150a772ee1d/packages/github/src/context.ts#L24-L29

**Comment by musketyr** [comment]
BTW I have scraped the values for the ENV variables for my own (currently abandoned) project but it might get handy for implementing GitHub Actions support:

https://github.com/agorapulse/ci/tree/master/src/test/resources/com/agorapulse/ci/GithubActionsSpec
